### ISSUE TITLE
lastest version error

### ISSUE THREAD

**Issue by ky0ncheng** [tea3/hexo-generator-amp#19]
INFO  Start processing
[hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently checking the cache now ...          [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently replacing table align now ...       [hexo-generator-amp] Plugin is currently restorating <figure> now ...        [hexo-generator-amp] Plugin is currently restorating <figure> now ...        [hexo-generator-amp] Plugin is currently restorating <figure> now ...        [hexo-generator-amp] Plugin is currently restorating <figure> now ...        [hexo-generator-amp] Plugin is currently restorating <figure> now ...        [hexo-generator-amp] Plugin is currently restorating <figure> now ...        [hexo-generator-amp] Plugin is currently restorating <figure> now ...        [hexo-generator-amp] Plugin is currently restorating <figure> now ...        [hexo-generator-amp] Plugin is currently restorating <figure> now ...        [hexo-generator-amp] Plugin is currently restorating <figure> now ...        [hexo-generator-amp] Plugin is currently replacing lazy video now ...        FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
ReferenceError: post is not defined
    at Object.<anonymous> (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:28:91)
    at initialize.exports.each (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/node_modules/cheerio/lib/api/traversing.js:300:24)
    at /Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:24:16
    at Promise._execute (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:77:14)
    at module.exports.filter_video (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:17:10)
    at tryCatcher (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
FATAL post is not defined
ReferenceError: post is not defined
    at Object.<anonymous> (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:28:91)
    at initialize.exports.each (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/node_modules/cheerio/lib/api/traversing.js:300:24)
    at /Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:24:16
    at Promise._execute (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:77:14)
    at module.exports.filter_video (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:17:10)
    at tryCatcher (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

delete `amp-template`, and remove and reinstall npm package,

`hexo g` again , then

INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
ReferenceError: post is not defined
    at Object.<anonymous> (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:28:91)
    at initialize.exports.each (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/node_modules/cheerio/lib/api/traversing.js:300:24)
    at /Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:24:16
    at Promise._execute (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:77:14)
    at module.exports.filter_video (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:17:10)
    at tryCatcher (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
FATAL post is not defined
ReferenceError: post is not defined
    at Object.<anonymous> (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:28:91)
    at initialize.exports.each (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/node_modules/cheerio/lib/api/traversing.js:300:24)
    at /Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:24:16
    at Promise._execute (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:77:14)
    at module.exports.filter_video (/Users/ky0n/Dropbox/Blog/node_modules/hexo-generator-amp/lib/filter/video.js:17:10)
    at tryCatcher (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/ky0n/Dropbox/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

https://github.com/tea3/hexo-generator-amp/commit/0e9f9be4a6008bbc55a9fbbb00d20fec73eb8515 This commit is wrong.

old version is ok.

**Comment by ky0ncheng** [comment]
Use theme with ejs or jade, error is same.

**Comment by tea3** [comment]
@ky0ncheng  Thank you . Please try new version.

```
$ npm uninstall hexo-generator-amp --save
$ npm install hexo-generator-amp --save
$ hexo new sample-diary-0206
$ hexo s
```

Please refer to the following for the detail .

https://hexo.io/docs/writing.html
https://github.com/tea3/hexo-generator-amp/issues/17#issuecomment-274698903

**Comment by ky0ncheng** [comment]
@tea3 Thank your for detailed answer!
